<a href="https://colab.research.google.com/github/hafezi1403/Hafezi.Video/blob/main/Deep%20Learning%20for%20Computer%20Vision%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [20]:
tensor_one_d=tf.constant([182,-1,15,83,9],dtype=tf.float32)
print(tensor_one_d )

tf.Tensor([182.  -1.  15.  83.   9.], shape=(5,), dtype=float32)


In [18]:
tensor_two_d=tf.constant([
    [2,94,-26],
    [3,10,-56],
    [3,10,-47],
    [0,2,-4]
    ])
print(tensor_two_d)

tf.Tensor(
[[  2  94 -26]
 [  3  10 -56]
 [  3  10 -47]
 [  0   2  -4]], shape=(4, 3), dtype=int32)


In [21]:
tensor_three_d=tf.constant([
    [[2,20,3],
     [3,4,5]],
    [[4,78,6],
     [5,46,7]],
    [[6,103,8],
    [7,8,999]],
])
print(tensor_three_d)

tf.Tensor(
[[[  2  20   3]
  [  3   4   5]]

 [[  4  78   6]
  [  5  46   7]]

 [[  6 103   8]
  [  7   8 999]]], shape=(3, 2, 3), dtype=int32)


In [22]:
print(tensor_three_d.shape)

(3, 2, 3)


In [23]:
print(tensor_three_d.ndim)

3


In [24]:
tensor_four_d = tf.constant([
[
    [[1,72,3],
     [3,4,59]],
    [[96,5,6],
     [5,6,32]],
    [[6,7,8],
    [7,13,9]],],

  [
    [[11,12,13],
     [3,42,5]],
    [[14,15,16],
     [5,16,7]],
    [[96,17,18],
    [7,48,9]],],

 [
    [[33,11,58],
     [3,42,59]],
    [[4,5,6],
     [5,16,87]],
    [[96,7,98],
    [7,48,93]],],
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1 72  3]
   [ 3  4 59]]

  [[96  5  6]
   [ 5  6 32]]

  [[ 6  7  8]
   [ 7 13  9]]]


 [[[11 12 13]
   [ 3 42  5]]

  [[14 15 16]
   [ 5 16  7]]

  [[96 17 18]
   [ 7 48  9]]]


 [[[33 11 58]
   [ 3 42 59]]

  [[ 4  5  6]
   [ 5 16 87]]

  [[96  7 98]
   [ 7 48 93]]]], shape=(3, 3, 2, 3), dtype=int32)


In [26]:
import numpy as np

In [25]:
np_array=np.array([1,2,3])
print (np_array)


[1 2 3]


In [11]:
converted_tensor = tf.convert_to_tensor(np_array)

In [27]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [28]:
print(eye_tensor*3)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [14]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [29]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [30]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)
